<?php // NOT NEEDED HERE > if ( ! defined('WOODMART_THEME_DIR')) exit('No direct script access allowed');

/**
 * ------------------------------------------------------------------------------------------------
 * CSS parts variables for CSS Generator
 * ------------------------------------------------------------------------------------------------
 */

return apply_filters(
	'woodmart_css_parts',
	array(
		/**
		 * WooCommerce styles.
		 */
		'wooComm'                       => array(
			'id'      => 'wooComm',
			'title'   => 'WooCommerce',
			'section' => 'WooCommerce styles',
			'checked' => true,
		),
		
		/**
		 * Products grid styles.
		 */
		'wc-shop'                       => array(
			'id'      => 'wc-shop',
			'title'   => 'Products grid styles',
			'section' => 'WooCommerce styles',
			'parent'  => 'wooComm',
			'checked' => true,
		),
		'hov-base'                      => array(
			'id'      => 'hov-base',
			'title'   => 'Hover base',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/products-grid-styles/grid-style-base.jpg',
		),
		'hov-alt'                       => array(
			'id'      => 'hov-alt',
			'title'   => 'Hover alternative',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/products-grid-styles/grid-style-alternative.jpg',
		),
		'hov-button'                    => array(
			'id'      => 'hov-button',
			'title'   => 'Hover button',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/products-grid-styles/grid-style-botton.jpg',
		),
		'hov-full-info'                 => array(
			'id'      => 'hov-full-info',
			'title'   => 'Hover full information',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/products-grid-styles/grid-style-full-information.jpg',
		),
		'hov-info-alt'                  => array(
			'id'      => 'hov-info-alt',
			'title'   => 'Full information alternative',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/products-grid-styles/grid-style-full-information-alternative.jpg',
		),
		'hov-quick'                     => array(
			'id'      => 'hov-quick',
			'title'   => 'Hover quick shop',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/products-grid-styles/grid--style-quik-shop.jpg',
		),
		'hov-standard'                  => array(
			'id'      => 'hov-standard',
			'title'   => 'Standard button',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/products-grid-styles/grid-style-standart-botton.jpg',
		),
		'hov-tiled'                     => array(
			'id'      => 'hov-tiled',
			'title'   => 'Tiled products',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/products-grid-styles/grid-style-tiled-products.jpg',
		),
		'hov-list'                      => array(
			'id'      => 'hov-list',
			'title'   => 'Products list',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/products-grid-styles/grid-style-list.jpg',
		),

		/**
		 * Product categories.
		 */
		'cat-general'                   => array(
			'id'      => 'cat-general',
			'title'   => 'Product categories',
			'section' => 'WooCommerce styles',
			'parent'  => 'wooComm',
			'checked' => true,
		),
		'cat-default'                   => array(
			'id'      => 'cat-default',
			'title'   => 'Default style',
			'section' => 'WooCommerce styles',
			'parent'  => 'cat-general',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/product-categories/categories-default.jpg',
		),
		'cat-alt'                       => array(
			'id'      => 'cat-alt',
			'title'   => 'Alternative style',
			'section' => 'WooCommerce styles',
			'parent'  => 'cat-general',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/product-categories/categories-alternative.jpg',
		),
		'cat-center'                    => array(
			'id'      => 'cat-center',
			'title'   => 'Centered style',
			'section' => 'WooCommerce styles',
			'parent'  => 'cat-general',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/product-categories/categories-centered.jpg',
		),
		'cat-title-rep'                 => array(
			'id'      => 'cat-title-rep',
			'title'   => 'Replace title',
			'section' => 'WooCommerce styles',
			'parent'  => 'cat-general',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/product-categories/categories-replace-title.jpg',
		),
		
		/**
		 * Modules.
		 */
		'wc-modules'                    => array(
			'id'      => 'wc-modules',
			'title'   => 'Modules',
			'section' => 'WooCommerce styles',
			'parent'  => 'wooComm',
			'checked' => true,
		),
		'quick-view'                    => array(
			'id'      => 'quick-view',
			'title'   => 'Quick view',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/modules/quik-view.jpg',
		),
		'size-guid'                     => array(
			'id'      => 'size-guid',
			'title'   => 'Size guide',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/modules/size-guide.jpg',
		),
		'stock-progress-bar'            => array(
			'id'      => 'stock-progress-bar',
			'title'   => 'Stock progress bar',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/modules/stock-progress-bar.jpg',
		),
		'add-to-cart-popup'             => array(
			'id'      => 'add-to-cart-popup',
			'title'   => 'Popup after add to cart',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/modules/add-to-cart-popup.jpg',
		),
		'rounded-product-labels'        => array(
			'id'      => 'rounded-product-labels',
			'title'   => 'Rounded product labels',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/modules/rounded-product-labels.jpg',
		),
		'rectangular-product-labels'    => array(
			'id'      => 'rectangular-product-labels',
			'title'   => 'Rectangular product labels',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/modules/rectangular-product-labels.jpg',
		),
		'highlight-prod'                => array(
			'id'      => 'highlight-prod',
			'title'   => 'Highlighted product',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/modules/highlighted-product.jpg',
		),
		'bordered-prod'                 => array(
			'id'      => 'bordered-prod',
			'title'   => 'Bordered product',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/modules/bordered.jpg',
		),
		'product-arrows'                 => array(
			'id'      => 'product-arrows',
			'title'   => 'Product arrows',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/modules/product-arrows.jpg',
		),
		'filter-area'                   => array(
			'id'      => 'filter-area',
			'title'   => 'Filters area',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/modules/filters-area.jpg',
		),
		'compare-prod'                  => array(
			'id'      => 'compare-prod',
			'title'   => 'Compare',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/modules/compare.jpg',
		),
		'wishlist'                      => array(
			'id'      => 'wishlist',
			'title'   => 'Wishlist',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/modules/wishlist.jpg',
		),
		
		/**
		 * Wc plugins.
		 */
		'wc-plugins'                    => array(
			'id'      => 'wc-plugins',
			'title'   => 'Plugins',
			'section' => 'WooCommerce styles',
			'parent'  => 'wooComm',
			'checked' => true,
		),
		'curr-switch'                   => array(
			'id'      => 'curr-switch',
			'title'   => 'Currency switcher',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-plugins',
			'checked' => true,
		),
		'germanized'                    => array(
			'id'      => 'germanized',
			'title'   => 'Germanized',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-plugins',
			'checked' => true,
		),
		'yith-vend'                     => array(
			'id'      => 'yith-vend',
			'title'   => 'YITH Vendors',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-plugins',
			'checked' => true,
		),
		'yith-wishlist'                 => array(
			'id'      => 'yith-wishlist',
			'title'   => 'YITH Wishlist',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-plugins',
			'checked' => false,
		),
		'yith-compare'                  => array(
			'id'      => 'yith-compare',
			'title'   => 'YITH Compare',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-plugins',
			'checked' => false,
		),
		'yith-request-quote'            => array(
			'id'      => 'yith-request-quote',
			'title'   => 'YITH Request a quote',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-plugins',
			'checked' => true,
		),
		'vc-vend'                       => array(
			'id'      => 'vc-vend',
			'title'   => 'WC Vendors',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-plugins',
			'checked' => true,
		),
		'dokon-vend'                    => array(
			'id'      => 'dokon-vend',
			'title'   => 'Dokan',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-plugins',
			'checked' => true,
		),
		'marketplace-vend'              => array(
			'id'      => 'marketplace-vend',
			'title'   => 'WC Marketplace',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-plugins',
			'checked' => true,
		),
		'wcfm-vend'                     => array(
			'id'      => 'wcfm-vend',
			'title'   => 'WCFM Marketplace',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-plugins',
			'checked' => false,
		),
		'paypal-express'                => array(
			'id'      => 'paypal-express',
			'title'   => 'PayPal express',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-plugins',
			'checked' => true,
		),
		'stripe'                        => array(
			'id'      => 'stripe',
			'title'   => 'Stripe',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-plugins',
			'checked' => true,
		),
		'advanced-nocaptcha'                        => array(
			'id'      => 'advanced-nocaptcha',
			'title'   => 'Advanced noCaptcha',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-plugins',
			'checked' => true,
		),
		
		/**
		 * Product page styles.
		 */
		'wc-product'                    => array(
			'id'      => 'wc-product',
			'title'   => 'Product page styles',
			'section' => 'WooCommerce styles',
			'parent'  => 'wooComm',
			'checked' => true,
		),
		'product-instagram'             => array(
			'id'      => 'product-instagram',
			'title'   => 'Product instagram',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/product-instagram.jpg',
		),
		'product-breadcrumbs'           => array(
			'id'      => 'product-breadcrumbs',
			'title'   => 'Product breadcrumbs',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/product-breadcrumbs.jpg',
		),
		'product-navigation'            => array(
			'id'      => 'product-navigation',
			'title'   => 'Product navigation',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/product-navigation.jpg',
		),
		'reviews'                       => array(
			'id'      => 'reviews',
			'title'   => 'Reviews',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/reviews.jpg',
		),
		'review-images'                       => array(
			'id'      => 'review-images',
			'title'   => 'Review images',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/review-images.jpg',
		),
		'product-share'                 => array(
			'id'      => 'product-share',
			'title'   => 'Product share',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/product-share.jpg',
		),
		'meta-location-summary'         => array(
			'id'      => 'meta-location-summary',
			'title'   => 'Meta location after add to cart',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/meta-location-summary.jpg',
		),
		'meta-location-after-tabs'      => array(
			'id'      => 'meta-location-after-tabs',
			'title'   => 'Meta location after tabs',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/meta-location-after-tabs.jpg',
		),
		'product-summary-shadow'        => array(
			'id'      => 'product-summary-shadow',
			'title'   => 'Product summary shadow',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/product-summary-shadow.jpg',
		),
		'single-product-brand'          => array(
			'id'      => 'single-product-brand',
			'title'   => 'Single product brand',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/single-product-brand.jpg',
		),
		'product-design-default'        => array(
			'id'      => 'product-design-default',
			'title'   => 'Product design default',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/product-design-default.jpg',
		),
		'product-design-centered'       => array(
			'id'      => 'product-design-centered',
			'title'   => 'Product design centered',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/product-design-centered.jpg',
		),
		'product-sidebar'               => array(
			'id'      => 'product-sidebar',
			'title'   => 'Product sidebar',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/product-sidebar.jpg',
		),
		'product-left-thumbnails'       => array(
			'id'      => 'product-left-thumbnails',
			'title'   => 'Product left thumbnails',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/product-left-thumbnails.jpg',
		),
		'product-bottom-thumbnails'     => array(
			'id'      => 'product-bottom-thumbnails',
			'title'   => 'Product bottom thumbnails',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/product-bottom-thumbnails.jpg',
		),
		'product-column-thumbnails'     => array(
			'id'      => 'product-column-thumbnails',
			'title'   => 'Product column thumbnails',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/product-column-thumbnails.gif',
		),
		'product-2-columns-thumbnails'  => array(
			'id'      => 'product-2-columns-thumbnails',
			'title'   => 'Product 2 columns thumbnails',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/product-2-columns-thumbnails.gif',
		),
		'product-combined-thumbnails'   => array(
			'id'      => 'product-combined-thumbnails',
			'title'   => 'Product combined thumbnails',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/product-combined-thumbnails.gif',
		),
		'product-centered-thumbnails'   => array(
			'id'      => 'product-centered-thumbnails',
			'title'   => 'Product centered thumbnails',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/product-centered-thumbnails.jpg',
		),
		'product-full-width-thumbnails' => array(
			'id'      => 'product-full-width-thumbnails',
			'title'   => 'Product full-width thumbnails',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/product-full-width-thumbnails.jpg',
		),
		'product-tabs'              => array(
			'id'      => 'product-tabs',
			'title'   => 'Product tabs',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/tabs-layout-tabs.jpg',
		),
		'product-thumbnail-buttons'     => array(
			'id'      => 'product-thumbnail-buttons',
			'title'   => 'Product thumbnail buttons',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/product-thumbnail-buttons.jpg',
		),
		'variable-product'              => array(
			'id'      => 'variable-product',
			'title'   => 'Variable product',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/variable-product.jpg',
		),
		'product-swatches'              => array(
			'id'      => 'product-swatches',
			'title'   => 'Product swatches',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/product-swatches.jpg',
		),
		'sticky-add-to-cart'            => array(
			'id'      => 'sticky-add-to-cart',
			'title'   => 'Sticky add to cart',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/sticky-addto-cart.jpg',
		),
		'grouped-product'               => array(
			'id'      => 'grouped-product',
			'title'   => 'Grouped product',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/grouped-product.jpg',
		),
		'upsells-widget'                => array(
			'id'      => 'upsells-widget',
			'title'   => 'Upsells widget',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-product',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/product-page/upsells-widget.jpg',
		),
		
		/**
		 * Shop page styles.
		 */
		'wc-shop-page'                  => array(
			'id'      => 'wc-shop-page',
			'title'   => 'Shop page styles',
			'section' => 'WooCommerce styles',
			'parent'  => 'wooComm',
			'checked' => true,
		),
		'shop-title-categories'         => array(
			'id'      => 'shop-title-categories',
			'title'   => 'Shop title categories',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/shop-page-styles/shop-title-categories.jpg',
		),
		'product-loader'                => array(
			'id'      => 'product-loader',
			'title'   => 'Product loader',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/shop-page-styles/product-loader.gif',
		),
		'active-filters'                => array(
			'id'      => 'active-filters',
			'title'   => 'Active filters',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/shop-page-styles/active-filters.jpg',
		),
		'result-count'                  => array(
			'id'      => 'result-count',
			'title'   => 'Result count',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/shop-page-styles/result-count.jpg',
		),
		'products-ordering'             => array(
			'id'      => 'products-ordering',
			'title'   => 'Products ordering',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/shop-page-styles/products-ordering.jpg',
		),
		'products-per-page'             => array(
			'id'      => 'products-per-page',
			'title'   => 'Products per page',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/shop-page-styles/products-per-page.jpg',
		),
		'shop-view'                     => array(
			'id'      => 'shop-view',
			'title'   => 'Shop products view',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/shop-page-styles/shop-view.jpg',
		),
		'woocommerce-pagination'        => array(
			'id'      => 'woocommerce-pagination',
			'title'   => 'Shop pagination',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/shop-page-styles/woocommerce-pagination.jpg',
		),
		'back-btn'        => array(
			'id'      => 'back-btn',
			'title'   => 'Back button',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/shop-page-styles/back-btn.jpg',
		),
		'without-title'        => array(
			'id'      => 'without-title',
			'title'   => 'Without title',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/shop-page-styles/without-title.jpg',
		),
		'shop-breadcrumbs' => array(
			'id'      => 'shop-breadcrumbs',
			'title'   => 'Shop breadcrumbs',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-shop-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/shop-page-styles/shop-breadcrumbs.jpg',
		),

		/**
		* WooCommerce pages.
		*/
		'wc-page'                       => array(
			'id'      => 'wc-page',
			'title'   => 'Pages',
			'section' => 'WooCommerce styles',
			'parent'  => 'wooComm',
			'checked' => true,
		),
		'cart'                          => array(
			'id'      => 'cart',
			'title'   => 'Cart',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/pages/cart.jpg',
		),
		'checkout'                      => array(
			'id'      => 'checkout',
			'title'   => 'Checkout',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/pages/checkout.jpg',
		),
		'login-register'                => array(
			'id'      => 'login-register',
			'title'   => 'Login & Register',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/pages/login-register.jpg',
		),
		'social-login'                  => array(
			'id'      => 'social-login',
			'title'   => 'Social login',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/pages/social-login.jpg',
		),
		'my-account'                    => array(
			'id'      => 'my-account',
			'title'   => 'My account',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/pages/my-account.jpg',
		),
		'order-page'                    => array(
			'id'      => 'order-page',
			'title'   => 'Order page',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/pages/order-page.jpg',
		),
		
		/**
		 * Widgets.
		 */
		'wc-widgets'                    => array(
			'id'      => 'wc-widgets',
			'title'   => 'Widgets',
			'section' => 'WooCommerce styles',
			'parent'  => 'wooComm',
			'checked' => true,
		),
		'layered-nav-widget'            => array(
			'id'      => 'layered-nav-widget',
			'title'   => 'Layered nav widget',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/widgets/layered-nav-widget.jpg',
		),
		'product-categories-widget'     => array(
			'id'      => 'product-categories-widget',
			'title'   => 'Product categoires widget',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/widgets/product-categories-widget.jpg',
		),
		'product-list-widget'           => array(
			'id'      => 'product-list-widget',
			'title'   => 'Product list widget',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/widgets/product-list-widget.jpg',
		),
		'price-filter-widget'           => array(
			'id'      => 'price-filter-widget',
			'title'   => 'Price filter widget',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/widgets/price-filter-widget.jpg',
		),
		'slider-price-filter-widget'    => array(
			'id'      => 'slider-price-filter-widget',
			'title'   => 'Slider price filter widget',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/widgets/slider-price-filter-widget.jpg',
		),
		'rating-filter-widget'          => array(
			'id'      => 'rating-filter-widget',
			'title'   => 'Filter products by rating',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/widgets/rating-filter-widget.jpg',
		),
		'attribute-filter-widget'       => array(
			'id'      => 'attribute-filter-widget',
			'title'   => 'Filter products by attribute',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/widgets/attribute-filter-widget.jpg',
		),
		'active-filters-widget'         => array(
			'id'      => 'active-filters-widget',
			'title'   => 'Active product filters',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/widgets/active-filters-widget.jpg',
		),
		'recent-reviews-widget'                   => array(
			'id'      => 'recent-reviews-widget',
			'title'   => 'Recent reviews widget',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/widgets/recent-reviews-widget.jpg',
		),
		'sort-by-widget'                => array(
			'id'      => 'sort-by-widget',
			'title'   => 'Sort by widget',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/widgets/sort-by-widget.jpg',
		),
		'cart-widget'                   => array(
			'id'      => 'cart-widget',
			'title'   => 'Cart widget',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/widgets/cart-widget.jpg',
		),
		'animations'                    => array(
			'id'      => 'animations',
			'title'   => 'Appearance animations',
			'section' => 'Extra features',
			'parent'  => 'wpbakery-elements-options',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/elemets-options/appearance-animations.gif',
		),
		'scroll-parallax'                    => array(
			'id'      => 'scroll-parallax',
			'title'   => 'Scroll parallax',
			'section' => 'Extra features',
			'parent'  => 'wpbakery-elements-options',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/elemets-options/scroll-parallax.gif',
		),
		'el-background-position'                    => array(
			'id'      => 'el-background-position',
			'title'   => 'Background position',
			'section' => 'Extra features',
			'parent'  => 'wpbakery-elements-options',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/elemets-options/background-position.gif',
		),

		/**
		 * Modules.
		 */
		'wc-extra_modules'              => array(
			'id'      => 'wc-extra_modules',
			'title'   => 'Modules',
			'section' => 'WooCommerce styles',
			'parent'  => 'wooComm',
			'checked' => true,
		),
		'woocommerce-notices'           => array(
			'id'      => 'woocommerce-notices',
			'title'   => 'Woocommerce notices',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-extra_modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/modules/woocommerce-notices.jpg',
		),
		'demo-store'                   => array(
			'id'      => 'demo-store',
			'title'   => 'Demo store notice',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-extra_modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/modules/demo-store.jpg',
		),
		'star-rating'                   => array(
			'id'      => 'star-rating',
			'title'   => 'Star rating',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-extra_modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/modules/star-rating.jpg',
		),
		'quantity'                   => array(
			'id'      => 'quantity',
			'title'   => 'Quantity buttons',
			'section' => 'WooCommerce styles',
			'parent'  => 'wc-extra_modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/woocommerce/extra-features/modules/quantity.jpg',
		),
		
		/**
		 * Extra configuration.
		 */
		'rtl'                           => array(
			'id'      => 'rtl',
			'title'   => 'RTL language',
			'section' => 'Extra configuration',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/extra/home-rtl.jpg',
		),
		'woodmart-dark'                 => array(
			'id'      => 'woodmart-dark',
			'title'   => 'Dark color scheme',
			'section' => 'Extra configuration',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/extra/demo-dark.jpg',
		),
		
		/**
		 * WPBakery Page Builder.
		 */
		'wpbakery'                      => array(
			'id'      => 'wpbakery',
			'title'   => 'WPBakery Page Builder',
			'section' => 'WPBakery elements',
			'checked' => true,
		),
		'wpbakery-base-elements'                      => array(
			'id'      => 'wpbakery-base-elements',
			'title'   => 'Base elements',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
		),
		'wpbakery-woo-elements'                      => array(
			'id'      => 'wpbakery-woo-elements',
			'title'   => 'WooCommerce elements',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
		),
		'el-brand'                      => array(
			'id'      => 'el-brand',
			'title'   => 'Brands',
			'section' => 'WooCommerce styles',
			'parent'  => 'wpbakery-woo-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/woo-elements/brands-element.jpg',
		),
		'el-product-tabs'               => array(
			'id'      => 'el-product-tabs',
			'title'   => 'Product tabs',
			'section' => 'WooCommerce styles',
			'parent'  => 'wpbakery-woo-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/woo-elements/products tabs.jpg',
		),
		'el-product-filters'            => array(
			'id'      => 'el-product-filters',
			'title'   => 'Product filters',
			'section' => 'WooCommerce styles',
			'parent'  => 'wpbakery-woo-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/woo-elements/el-product-filters.jpg',
		),
		'el-add-to-cart'                => array(
			'id'      => 'el-add-to-cart',
			'title'   => 'Add to cart',
			'section' => 'WooCommerce styles',
			'parent'  => 'wpbakery-woo-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/woo-elements/el-add-to-cart.jpg',
		),
		'banner'                        => array(
			'id'      => 'banner',
			'title'   => 'Promo banner',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-base-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/base-elements/banners.jpg',
		),
		'timer'                         => array(
			'id'      => 'timer',
			'title'   => 'Countdown timer',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-base-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/base-elements/countdown-timer.jpg',
		),
		'counter'                       => array(
			'id'      => 'counter',
			'title'   => 'Counter',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-base-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/base-elements/animated-counter.jpg',
		),
		'map'                           => array(
			'id'      => 'map',
			'title'   => 'Google map',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-base-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/base-elements/google-maps.jpg',
		),
		'gallery'                       => array(
			'id'      => 'gallery',
			'title'   => 'Images gallery',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-base-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/base-elements/images-gallery.jpg',
		),
		'hotspot'                       => array(
			'id'      => 'hotspot',
			'title'   => 'Images hotspot',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-woo-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/woo-elements/image-hotspot.jpg',
		),
		'info-box'                      => array(
			'id'      => 'info-box',
			'title'   => 'Information box',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-base-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/base-elements/infobox.jpg',
		),
		'instagram'                     => array(
			'id'      => 'instagram',
			'title'   => 'Instagram',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-base-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/base-elements/instagram.jpg',
		),
		'list'                          => array(
			'id'      => 'list',
			'title'   => 'Icon list',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-base-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/base-elements/list-element.jpg',
		),
		'menu-price'                    => array(
			'id'      => 'menu-price',
			'title'   => 'Menu price',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-base-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/base-elements/menu-price.jpg',
		),
		'pricing-table'                 => array(
			'id'      => 'pricing-table',
			'title'   => 'Pricing table',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-woo-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/woo-elements/pricing-tables.jpg',
		),
		'row-divider'                   => array(
			'id'      => 'row-divider',
			'title'   => 'Row divider',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-base-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/base-elements/section-dividers.jpg',
		),
		'sec-title'                     => array(
			'id'      => 'sec-title',
			'title'   => 'Section title',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-base-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/base-elements/titles.jpg',
		),
		'responsive-text'               => array(
			'id'      => 'responsive-text',
			'title'   => 'Responsive text block',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-base-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/base-elements/responsive-text-block.jpg',
		),
		'slider'                        => array(
			'id'      => 'slider',
			'title'   => 'WoodMart slider',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-base-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/base-elements/sliders.jpg',
		),
		'team-member'                   => array(
			'id'      => 'team-member',
			'title'   => 'Team member',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-base-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/base-elements/team-member.jpg',
		),
		'author-area'                   => array(
			'id'      => 'author-area',
			'title'   => 'Author area',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-base-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/base-elements/author-area.jpg',
		),
		'testimonial'                   => array(
			'id'      => 'testimonial',
			'title'   => 'Testimonials',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-base-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/base-elements/testimonials.jpg',
		),
		'timeline'                      => array(
			'id'      => 'timeline',
			'title'   => 'Timeline',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-base-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/base-elements/timeline.jpg',
		),
		'twitter'                       => array(
			'id'      => 'twitter',
			'title'   => 'Twitter',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-base-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/base-elements/twiter-wb.jpg',
		),
		'deg360'                        => array(
			'id'      => 'deg360',
			'title'   => '360 degree view',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-base-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/base-elements/360-degree-view.jpg',
		),
		'progress-bar'                  => array(
			'id'      => 'progress-bar',
			'title'   => 'Progress bar',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-base-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/base-elements/progress-bar.jpg',
		),
		'video-element'                  => array(
			'id'      => 'video-element',
			'title'   => 'Video',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-base-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/base-elements/video-element.jpg',
		),
		'single-image'                  => array(
			'id'      => 'single-image',
			'title'   => 'Single image',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-base-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/base-elements/single-image.jpg',
		),
		'wpb-accordion'                  => array(
			'id'      => 'wpb-accordion',
			'title'   => 'WPB Accordion',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-base-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/base-elements/vc-acordion.jpg',
		),
		'wpb-tabs'                       => array(
			'id'      => 'wpb-tabs',
			'title'   => 'WPB Tabs',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-base-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/base-elements/vc-tabs.jpg',
		),
		'track-order'                   => array(
			'id'      => 'track-order',
			'title'   => 'Order tracking form',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery-woo-elements',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wpbakery-page-builder/woo-elements/track-order.jpg',
		),
		'wpbakery-elements-options'     => array(
			'id'      => 'wpbakery-elements-options',
			'title'   => 'Elements options',
			'section' => 'WPBakery elements',
			'parent'  => 'wpbakery',
			'checked' => true,
		),
		
		/**
		 * Additional plugins.
		 */
		'extra-plugins'                 => array(
			'id'      => 'extra-plugins',
			'title'   => 'Plugins',
			'section' => 'Additional plugins',
			'checked' => true,
		),
		'bbpress'                       => array(
			'id'      => 'bbpress',
			'title'   => 'BBPress',
			'section' => 'Additional plugins',
			'parent'  => 'extra-plugins',
			'checked' => false,
		),
		'wpcf7'                         => array(
			'id'      => 'wpcf7',
			'title'   => 'Contact form 7',
			'section' => 'Additional plugins',
			'parent'  => 'extra-plugins',
			'checked' => true,
		),
		'mc4wp'                         => array(
			'id'      => 'mc4wp',
			'title'   => 'Mailchimp',
			'section' => 'Additional plugins',
			'parent'  => 'extra-plugins',
			'checked' => true,
		),
		'wpml'                          => array(
			'id'      => 'wpml',
			'title'   => 'WPML',
			'section' => 'Additional plugins',
			'parent'  => 'extra-plugins',
			'checked' => true,
		),
		
		/**
		 * Portfolio.
		 */
		'portfolio'                     => array(
			'id'      => 'portfolio',
			'title'   => 'Portfolio styles',
			'section' => 'Portfolio',
			'checked' => true,
		),
		'project-hover'                 => array(
			'id'      => 'project-hover',
			'title'   => 'Portfolio base hover',
			'section' => 'Portfolio',
			'parent'  => 'portfolio',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/portfolio/portfolio-base-hover.jpg',
		),
		'project-Alt'                   => array(
			'id'      => 'project-Alt',
			'title'   => 'Alternate hover',
			'section' => 'Portfolio',
			'parent'  => 'portfolio',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/portfolio/alternative-hover.jpg',
		),
		'project-under'                 => array(
			'id'      => 'project-under',
			'title'   => 'Title under image',
			'section' => 'Portfolio',
			'parent'  => 'portfolio',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/portfolio/title-under-image.jpg',
		),
		'project-parallax'              => array(
			'id'      => 'project-parallax',
			'title'   => 'Parallax on mouse move',
			'section' => 'Portfolio',
			'parent'  => 'portfolio',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/portfolio/parallax-mouse-move.jpg',
		),
		
		/**
		 * Wordpress.
		 */

		'wordpress-styles'                   => array(
			'id'      => 'wordpress-styles',
			'title'   => 'WordPress',
			'section' => 'Wordpress',
			'checked' => true,
		),
		'blog-styles'                   => array(
			'id'      => 'blog-styles',
			'title'   => 'Blog styles',
			'section' => 'Wordpress',
			'parent'  => 'wordpress-styles',
			'checked' => true,
		),
		'blog-default'                  => array(
			'id'      => 'blog-default',
			'title'   => 'Default',
			'section' => 'Wordpress',
			'parent'  => 'blog-styles',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/blog-styles/default.jpg',
		),
		'blog-alt'                      => array(
			'id'      => 'blog-alt',
			'title'   => 'Alternative',
			'section' => 'Wordpress',
			'parent'  => 'blog-styles',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/blog-styles/alternative.jpg',
		),
		'blog-small-img'                => array(
			'id'      => 'blog-small-img',
			'title'   => 'Small images',
			'section' => 'Wordpress',
			'parent'  => 'blog-styles',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/blog-styles/small-images.jpg',
		),
		'blog-chess'                    => array(
			'id'      => 'blog-chess',
			'title'   => 'Chess grid',
			'section' => 'Wordpress',
			'parent'  => 'blog-styles',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/blog-styles/chess-grid.jpg',
		),
		'blog-mask'                     => array(
			'id'      => 'blog-mask',
			'title'   => 'Image mask',
			'section' => 'Wordpress',
			'parent'  => 'blog-styles',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/blog-styles/image-mask.jpg',
		),
		'post-page'                    => array(
			'id'      => 'post-page',
			'title'   => 'Post page styles',
			'section' => 'Wordpress',
			'parent'  => 'wordpress-styles',
			'checked' => true,
		),
		'post-design-large-image'                    => array(
			'id'      => 'post-design-large-image',
			'title'   => 'Post design large image',
			'section' => 'Wordpress',
			'parent'  => 'post-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/post-page-styles/post-design-large-image.jpg',
		),
		'justified-gallery'                    => array(
			'id'      => 'justified-gallery',
			'title'   => 'Justified gallery',
			'section' => 'Wordpress',
			'parent'  => 'post-page',
			'checked' => false,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/post-page-styles/justified-gallery.jpg',
		),
		'author-info'                    => array(
			'id'      => 'author-info',
			'title'   => 'Author info',
			'section' => 'Wordpress',
			'parent'  => 'post-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/post-page-styles/author-info.jpg',
		),
		'post-meta'                    => array(
			'id'      => 'post-meta',
			'title'   => 'Meta tags',
			'section' => 'Wordpress',
			'parent'  => 'post-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/post-page-styles/post-meta.jpg',
		),
		'post-social'                    => array(
			'id'      => 'post-social',
			'title'   => 'Social buttons',
			'section' => 'Wordpress',
			'parent'  => 'post-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/post-page-styles/post-social.jpg',
		),
		'comments'                     => array(
			'id'      => 'comments',
			'title'   => 'Comments',
			'section' => 'Wordpress',
			'parent'  => 'post-page',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/post-page-styles/comments.jpg',
		),

		/**
		 * WP Pages.
		 */
		'wp-pages'                    => array(
			'id'      => 'wp-pages',
			'title'   => 'Pages',
			'section' => 'Wordpress',
			'parent'  => 'wordpress-styles',
			'checked' => true,
		),
		'page-404'                    => array(
			'id'      => 'page-404',
			'title'   => '404 page',
			'section' => 'Pages',
			'parent'  => 'wp-pages',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/pages/page-404.jpg',
		),

		/**
		 * WP Modules.
		 */
		'wp-modules'                   => array(
			'id'      => 'wp-modules',
			'title'   => 'Modules',
			'section' => 'Wordpress',
			'parent'  => 'wordpress-styles',
			'checked' => true,
		),
		'gutenberg'                    => array(
			'id'      => 'gutenberg',
			'title'   => 'Gutenberg editor',
			'section' => 'Wordpress',
			'parent'  => 'wp-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/modules/gutenberg.jpg',
		),
		'page-navigation'              => array(
			'id'      => 'page-navigation',
			'title'   => 'Page navigation',
			'section' => 'Wordpress',
			'parent'  => 'wp-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/modules/page-navigation.jpg',
		),
		'wp-breadcrumbs'               => array(
			'id'      => 'wp-breadcrumbs',
			'title'   => 'Breadcrumbs',
			'section' => 'Wordpress',
			'parent'  => 'wp-modules',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/modules/wp-breadcrumbs.jpg',
		),

		/**
		 * WP Widgets.
		 */
		'wp-widgets'                   => array(
			'id'      => 'wp-widgets',
			'title'   => 'Widgets',
			'section' => 'Wordpress',
			'parent'  => 'wordpress-styles',
			'checked' => true,
		),
		'calendar-widget'              => array(
			'id'      => 'calendar-widget',
			'title'   => 'Calendar',
			'section' => 'Wordpress',
			'parent'  => 'wp-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/widgets/calendar-widget.jpg',
		),
		'recent-comments-widget'       => array(
			'id'      => 'recent-comments-widget',
			'title'   => 'Recent comments',
			'section' => 'Wordpress',
			'parent'  => 'wp-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/widgets/recent-comments-widget.jpg',
		),
		'recent-posts-widget'          => array(
			'id'      => 'recent-posts-widget',
			'title'   => 'Recent posts',
			'section' => 'Wordpress',
			'parent'  => 'wp-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/widgets/recent-posts-widget.jpg',
		),
		'wd-recent-posts-widget'       => array(
			'id'      => 'wd-recent-posts-widget',
			'title'   => 'Woodmart recent posts',
			'section' => 'Wordpress',
			'parent'  => 'wp-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/widgets/wd-recent-posts-widget.jpg',
		),
		'rss-widget'                   => array(
			'id'      => 'rss-widget',
			'title'   => 'RSS widget',
			'section' => 'Wordpress',
			'parent'  => 'wp-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/widgets/rss-widget.jpg',
		),
		'nav-mega-menu-widget'         => array(
			'id'      => 'nav-mega-menu-widget',
			'title'   => 'Mega menu',
			'section' => 'Wordpress',
			'parent'  => 'wp-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/widgets/nav-mega-menu-widget.jpg',
		),
		'tag-cloud-widget'             => array(
			'id'      => 'tag-cloud-widget',
			'title'   => 'Tag cloud',
			'section' => 'Wordpress',
			'parent'  => 'wp-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/widgets/tag-cloud-widget.jpg',
		),
		'categories-widget'            => array(
			'id'      => 'categories-widget',
			'title'   => 'Categories',
			'section' => 'Wordpress',
			'parent'  => 'wp-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/widgets/categories-widget.jpg',
		),
		'archive-widget'               => array(
			'id'      => 'archive-widget',
			'title'   => 'Archive',
			'section' => 'Wordpress',
			'parent'  => 'wp-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/widgets/archive-widget.jpg',
		),
		'pages-widget'                 => array(
			'id'      => 'pages-widget',
			'title'   => 'Pages',
			'section' => 'Wordpress',
			'parent'  => 'wp-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/widgets/pages-widget.jpg',
		),
		'nav-widget'                   => array(
			'id'      => 'nav-widget',
			'title'   => 'Menu navigation',
			'section' => 'Wordpress',
			'parent'  => 'wp-widgets',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/wordpress/widgets/nav-widget.jpg',
		),
		
		/**
		 * Extra features.
		 */
		'extra-features'                => array(
			'id'      => 'extra-features',
			'title'   => 'Features',
			'section' => 'Extra features',
			'checked' => true,
		),
		'off-canvas-sidebar'            => array(
			'id'      => 'off-canvas-sidebar',
			'title'   => 'Off-canvas sidebar',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/off-canvas-sidebar.jpg',
		),
		'nanoscroller'                     => array(
			'id'      => 'nanoscroller',
			'title'   => 'Nanoscroller library',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/nanoscroller.gif',
		),
		'wrapper-boxed'                     => array(
			'id'      => 'wrapper-boxed',
			'title'   => 'Content wrapper boxed',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/wrapper-boxed.jpg',
		),
		'lazy-load'                     => array(
			'id'      => 'lazy-load',
			'title'   => 'Image lazy loading',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/lazy-load.gif',
		),
		'scrolltotop'                     => array(
			'id'      => 'scrolltotop',
			'title'   => 'Scroll to top button',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/scrolltotop.jpg',
		),
		'sticky-footer'                     => array(
			'id'      => 'sticky-footer',
			'title'   => 'Sticky footer',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/sticky-footer.gif',
		),
		'footer-copyrights'                     => array(
			'id'      => 'footer-copyrights',
			'title'   => 'Footer copyrights',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/footer-copyrights.jpg',
		),
		'footer-widget-collapse'                     => array(
			'id'      => 'footer-widget-collapse',
			'title'   => 'Footer widget collapse',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/footer-widget-collapse.jpg',
		),
		'header-banner'                 => array(
			'id'      => 'header-banner',
			'title'   => 'Header banner',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/header-banner.jpg',
		),
		'social-icons'                => array(
			'id'      => 'social-icons',
			'title'   => 'Social icons',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/social-icons.jpg',
		),
		'sticky-social'                => array(
			'id'      => 'sticky-social',
			'title'   => 'Sticky social',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/sticky-social.jpg',
		),
		'tooltips'                => array(
			'id'      => 'tooltips',
			'title'   => 'Tooltips',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/tooltips.jpg',
		),
		'menu-label'                => array(
			'id'      => 'menu-label',
			'title'   => 'Menu label',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/menu-label.jpg',
		),
		'bottom-toolbar'                => array(
			'id'      => 'bottom-toolbar',
			'title'   => 'Bottom toolbar',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/bottom-toolbar.jpg',
		),
		'cookies'                       => array(
			'id'      => 'cookies',
			'title'   => 'Cookies notice',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/cookies-notice.jpg',
		),
		'wd-search'                        => array(
			'id'      => 'wd-search',
			'title'   => 'Search form',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/search-form.jpg',
		),
		'underline-menu'                     => array(
			'id'      => 'underline-menu',
			'title'   => 'Underline menu',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/underline-menu.jpg',
		),
		'bordered-menu'                     => array(
			'id'      => 'bordered-menu',
			'title'   => 'Bordered menu',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/bordered-menu.jpg',
		),
		'separated-menu'                     => array(
			'id'      => 'separated-menu',
			'title'   => 'Separated menu',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/separated-menu.jpg',
		),
		'vertical-navigation'                     => array(
			'id'      => 'vertical-navigation',
			'title'   => 'Vertical menu',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/vertical-navigation.jpg',
		),
		'more-categories-button'                     => array(
			'id'      => 'more-categories-button',
			'title'   => 'Vertical menu more button',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/more-categories-button.jpg',
		),
		'full-menu'                     => array(
			'id'      => 'full-menu',
			'title'   => 'Header full screen menu',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/header-full-screen-menu.jpg',
		),
		'ol-ul-list'                    => array(
			'id'      => 'ol-ul-list',
			'title'   => 'Standard ul and ol styles',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/standard-ul-ol-styles.jpg',
		),
		'form-rounded'                  => array(
			'id'      => 'form-rounded',
			'title'   => 'Rounded forms style',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/form-rounded.jpg',
		),
		'form-circle'                   => array(
			'id'      => 'form-circle',
			'title'   => 'Circled forms style',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/form-circle.jpg',
		),
		'form-underline'                => array(
			'id'      => 'form-underline',
			'title'   => 'Underlined forms style',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/form-underline.jpg',
		),
		'header-dropdown-dark'          => array(
			'id'      => 'header-dropdown-dark',
			'title'   => 'Header dropdowns dark style',
			'section' => 'Extra features',
			'parent'  => 'extra-features',
			'checked' => true,
			'image'   => WOODMART_DEMO_URL . 'css-generator-tooltips-4-2/features/header-dropdown-dark.jpg',
		),
	)
);
